### PR TITLE
Added new commands: .str and some code optimizations

### PR DESCRIPTION
**Pull request by flamecyclone**
Made some minor changes to make it easier to read

### CODE REVIEW

**Comment by flamecyclone** [comment]
Before adding the .str command, if I need to define a string, assuming that the first byte stores the length of the string, I define it like this:
  .DB 09,"RAF WORLD"
I need to manually calculate the length of the string, if there are multiple strings, all this will become very cumbersome.

But after I added the .str command, this operation will become easier
  .STR "RAF WORLD"

This is the effect after I use the .str command:
image

**Comment by ClusterM** [comment]
Great! Can you add **.str** description to the README.md file?

**Comment by flamecyclone** [comment]
Sure, but my network at home doesn't access GitHub properly, so I'll add .str usage to the readme when I go to work tomorrow




FlameCyclone
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ClusterM/nesasm"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月7日(星期一) 晚上9:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ClusterM/nesasm] Added new commands: .str and some code optimizations (PR #5)





 
Great! Can you add .str description to the README.md file?

**Comment by flamecyclone** [comment]
> Great! Can you add **.str** description to the README.md file?

I've updated the readme description, you review it

**Comment by ClusterM** [comment]
Thank you!

**Comment by flamecyclone** [comment]
You're welcome. This is what I should do.

**Pull request merged**
